[package]
name = "sgl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
image = "0.24.5"
bytemuck = "1.13.0"
field-offset = "0.3.4"
enumflags2 = "0.7.5"